#spring.mail.host=smtp.hostinger.com
#spring.mail.port=587
#spring.mail.username=soporteweb@representacionesdelsur.com
#spring.mail.password=Soporteweb9.
#
#spring.mail.protocol=smtp
#spring.mail.properties.transport.protocol=smtp
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring:
  mail:
    host: smtp.hostinger.com
    port: 587
    username: marketing@representacionesdelsur.com
    password: Marketing123$
    protocol: smtp
    properties:
      transport:
        protocol: smtp
      mail:
        smtp:
          auth: true
          starttls:
            enable: true